// selecting of an Element

// let a = document.querySelector("h1")
//  console.log(a);


// changed HTML
//  var a = document.querySelector("h1")
//  a.innerHTML = "changed element"

 // changed css

//  var a = document.querySelector("h1")
//  a.style.color ="red"
 

//Event listener

// var a = document.querySelector("h1")
// a.addEventListener ("click" ,function(){
//     a.innerHTML = "changed element"
//     a.style.color = "yellow"


// })


// example on off click btn